### PR TITLE
Fix the initial candidate window position

### LINKED ISSUE #2792: The initial IME candidate window position is wrong
### Is your issue REALLY a bug?

- [x] My issue is indeed a bug!
- [x] I am not crazy! I will not fill out this form just to ask a question or request a feature. Pinky promise.

### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Is this issue related to iced?

- [x] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

1. Open TODO example
2. Focus the text input
3. Activate IME
4. Type any key
5. The candidate window appears at the top left corner of the window

This only happens when the candidate is firstly opened (`あいうえお`). When opening the window for the second time, the position is correct (`かきくけこ`).

https://github.com/user-attachments/assets/49c0bbfe-44e8-4058-b70a-d524b9d7dc12

### What is the expected behavior?

The position of the candidate window should be near the cursor on opening it for the first time.

### Version

master

### Operating System

macOS

### Do you have any log output?

```shell

```

### PR DESCRIPTION
**Pull request by rhysd**
Fixes #2792. Closes #2800.

The issue is that the candidate window is already open when `InputMethod::Open` event is handled in the window manager. Since `set_ime_cursor_area` is not called yet when the window is opened, the position of the window is at the top left corner.

To fix this, we need to call `set_ime_cursor_area` earlier before the window is opened. [winit's example](https://github.com/rust-windowing/winit/blob/2230e71093a110d959c245b639faf67a60dca135/examples/window.rs#L687-L690) calls the function just after calling `set_ime_allowed`.

This PR calls the function when allowing IME so `InputMethod::Allowed` event now has the position of the window.

Here is the video:

https://github.com/user-attachments/assets/c8d21b64-71f3-4ff5-80d4-3ddfa6b20718

### CODE REVIEW

**Comment by kenz-gelsoft** [comment]
I think this is sane fix for the problem I catched earlier on original PR:

https://github.com/iced-rs/iced/pull/2777#issuecomment-2631192585

I investigated winit macOS code and I find it correctly updates the position of the ime_position internally and invalidates it when we call winit::Window::set_ime_cursor_area().

But as far as I tested macOS iuput methods doesn't reposition immediately while it is currently displayed.

So this is not a bug of winit and is a cross platform limitation. We need to set_ime_cursor_area() before the subsequent Preedit input method event I guess.

Sorry about the misinformation on the decision of the initial API design.

**Comment by kenz-gelsoft** [comment]
How about merging Allowed and Open state like this?

https://github.com/kenz-gelsoft/iced/commit/3cfe5eb2d31ffaef01770ff5f47be5bdf5553443

**Comment by rhysd** [comment]
That sounds also work and it's simpler. One downside on it is that `window.set_ime_allowed` is called every time when the preedit content is updated. I don't know how `window.set_ime_allowed` is implemented in winit, but the usage would be fairly irregular.

**Comment by rhysd** [comment]
But I have an idea for avoiding the downside.

So I'd like to suggest to make a PR with [the commit](https://github.com/kenz-gelsoft/iced/commit/3cfe5eb2d31ffaef01770ff5f47be5bdf5553443) by @kenz-gelsoft and then I will send a PR to your fork.

**Comment by kenz-gelsoft** [comment]
@hecrj Sorry for disturbing, I proposed merging Allowed and Open states in this PR, but it was not simple to handle in this PR.

I think this PR should be included in the first release which support input method.

Please review this as-is.

**Review by hecrj — APPROVED** [review]
I have simplified the `InputMethod` API to have only 2 states: `Disabled` and `Enabled`.

Could you test and make sure everything works as expected?

**Comment by rhysd** [comment]
@hecrj Thank you for reworking my patch. As far as I tried, it worked fine. (Checked only `TextInput` for my usage)

**Comment by rhysd** [comment]
One possible improvement is splitting checks for `position` and `purpose` so that the number of each low-level API calls can be reduced. `position` frequently changes but `purpose` changes only once when the text input is activated. So calling `set_ime_purpose` for each time when the position changes is a bit redundant.

```diff
diff --git a/winit/src/program/window_manager.rs b/winit/src/program/window_manager.rs
index 25d3ad9c..b2f53546 100644
--- a/winit/src/program/window_manager.rs
+++ b/winit/src/program/window_manager.rs
@@ -259,18 +259,19 @@ where
     }
 
     fn enable_ime(&mut self, position: Point, purpose: input_method::Purpose) {
-        if self.ime_state.is_none() {
-            self.raw.set_ime_allowed(true);
-        }
-
-        if self.ime_state != Some((position, purpose)) {
-            self.raw.set_ime_cursor_area(
-                LogicalPosition::new(position.x, position.y),
-                LogicalSize::new(10, 10), // TODO?
-            );
-            self.raw.set_ime_purpose(conversion::ime_purpose(purpose));
-
+        if let Some((prev_position, prev_purpose)) = self.ime_state {
+            if prev_position != position {
+                self.raw.set_ime_cursor_area(
+                    LogicalPosition::new(position.x, position.y),
+                    LogicalSize::new(10, 10), // TODO?
+                );
+            }
+            if prev_purpose != purpose {
+                self.raw.set_ime_purpose(conversion::ime_purpose(purpose));
+            }
             self.ime_state = Some((position, purpose));
+        } else {
+            self.raw.set_ime_allowed(true);
         }
     }
 
```

**Comment by kenz-gelsoft** [comment]
> I have simplified the `InputMethod` API to have only 2 states: `Disabled` and `Enabled`.
> 
> Could you test and make sure everything works as expected?

Yes, I will test and respond you today.

**Comment by rhysd** [comment]
I could reproduce it on macOS too.

**Comment by kenz-gelsoft** [comment]
Markdown example works fine, so this is text_input specific.

**Comment by kenz-gelsoft** [comment]
Committed preedit remains there on Windows

image

**Comment by hecrj** [comment]
Are these new issues or are they present in `master`?

File: widget/src/text_input.rs [hunk 1]
```diff
@@ -1340,6 +1336,12 @@ where
                                 millis_until_redraw as u64,
                             ),
                         );
+
+                        shell.request_input_method(&self.input_method(
+                            state,
+                            layout,
+                            &self.value,
+                        ));
```
Comment (kenz-gelsoft) [inline widget/src/text_input.rs:1344]: We moved request_input_method() here which called only if cursor is Index arm.

This looks the cause of problem 1.

**Comment by kenz-gelsoft** [comment]
> Are these new issues or are they present in `master`?

Sorry I don't have enough time to check that now. I will test that tonight (15hrs later or so).

File: widget/src/text_input.rs (hunk 1 above)
Comment (hecrj) [reply widget/src/text_input.rs:1345]: Fixed in f62529747570144eb3e4822dde514d46a65b86ee.

**Comment by hecrj** [comment]
I'm guessing the problem on Windows comes from `winit` not issuing an empty `Preedit` event before a `Commit`.

We can manually reset the preedit anyways. Done that in d6d88da96a13cf14a6886545d1c6e75e527fc694.

**Comment by rhysd** [comment]
I tried b399ef1 but the pre-edit window is still not cleared after commiting the candidate.

**Comment by hecrj** [comment]
@rhysd Is it just the overlay not clearing or does the text also not get inserted in the input?

**Comment by rhysd** [comment]
I can't take time to record video for now. Let me try it tonight.

**Comment by rhysd** [comment]
I applied the following patch and observed the log.

```diff
diff --git a/widget/src/text_input.rs b/widget/src/text_input.rs
index ae3dfe4c..8743a376 100644
--- a/widget/src/text_input.rs
+++ b/widget/src/text_input.rs
@@ -1266,6 +1266,7 @@ where
                     let state = state::<Renderer>(tree);

                     if state.is_focused.is_some() {
+                        dbg!(("input_method::Event::Preedit", content));
                         state.preedit = Some(input_method::Preedit {
                             content: content.to_owned(),
                             selection: selection.clone(),
@@ -1338,6 +1339,10 @@ where
                             );
                         }

+                        dbg!((
+                            "input_method::Event::Preedit",
+                            state.preedit.as_ref().map(|p| &p.content)
+                        ));
                         shell.request_input_method(&self.input_method(
                             state,
                             layout,
```

I entered "あいうえお" via IME and commited it by Enter.

```
[widget\src\text_input.rs:1342:25] ("input_method::Event::Preedit", state.preedit.as_ref().map(|p| &p.content)) = (
    "input_method::Event::Preedit",
    None,
)
[widget\src\text_input.rs:1269:25] ("input_method::Event::Preedit", content) = (
    "input_method::Event::Preedit",
    "あ",
)
[widget\src\text_input.rs:1342:25] ("input_method::Event::Preedit", state.preedit.as_ref().map(|p| &p.content)) = (
    "input_method::Event::Preedit",
    Some(
        "あ",
    ),
)
[widget\src\text_input.rs:1342:25] ("input_method::Event::Preedit", state.preedit.as_ref().map(|p| &p.content)) = (
    "input_method::Event::Preedit",
    Some(
        "あ",
    ),
)
[widget\src\text_input.rs:1269:25] ("input_method::Event::Preedit", content) = (
    "input_method::Event::Preedit",
    "あい",
)
[widget\src\text_input.rs:1342:25] ("input_method::Event::Preedit", state.preedit.as_ref().map(|p| &p.content)) = (
    "input_method::Event::Preedit",
    Some(
        "あい",
    ),
)
[widget\src\text_input.rs:1342:25] ("input_method::Event::Preedit", state.preedit.as_ref().map(|p| &p.content)) = (
    "input_method::Event::Preedit",
    Some(
        "あい",
    ),
)
[widget\src\text_input.rs:1269:25] ("input_method::Event::Preedit", content) = (
    "input_method::Event::Preedit",
    "あいう",
)
[widget\src\text_input.rs:1342:25] ("input_method::Event::Preedit", state.preedit.as_ref().map(|p| &p.content)) = (
    "input_method::Event::Preedit",
    Some(
        "あいう",
    ),
)
[widget\src\text_input.rs:1269:25] ("input_method::Event::Preedit", content) = (
    "input_method::Event::Preedit",
    "あいうえ",
)
[widget\src\text_input.rs:1342:25] ("input_method::Event::Preedit", state.preedit.as_ref().map(|p| &p.content)) = (
    "input_method::Event::Preedit",
    Some(
        "あいうえ",
    ),
)
[widget\src\text_input.rs:1342:25] ("input_method::Event::Preedit", state.preedit.as_ref().map(|p| &p.content)) = (
    "input_method::Event::Preedit",
    Some(
        "あいうえ",
    ),
)
[widget\src\text_input.rs:1269:25] ("input_method::Event::Preedit", content) = (
    "input_method::Event::Preedit",
    "あいうえお",
)
[widget\src\text_input.rs:1342:25] ("input_method::Event::Preedit", state.preedit.as_ref().map(|p| &p.content)) = (
    "input_method::Event::Preedit",
    Some(
        "あいうえお",
    ),
)
[widget\src\text_input.rs:1269:25] ("input_method::Event::Preedit", content) = (
    "input_method::Event::Preedit",
    "",
)
[widget\src\text_input.rs:1342:25] ("input_method::Event::Preedit", state.preedit.as_ref().map(|p| &p.content)) = (
    "input_method::Event::Preedit",
    None,
)
```

The bug is that, although `input_method::Event::Preedit` is emitted from winit correctly with empty content, the preedit content is set to `None` when `window::Event::RedrawRequested` is emitted. Since the preedit window content is cleared only when the content is an empty string, the window is not cleared.

```
[widget\src\text_input.rs:1269:25] ("input_method::Event::Preedit", content) = (
    "input_method::Event::Preedit",
    "",
)
[widget\src\text_input.rs:1342:25] ("input_method::Event::Preedit", state.preedit.as_ref().map(|p| &p.content)) = (
    "input_method::Event::Preedit",
    None,
)
```

It seems that the `shell.request_redraw()` call at `input_method::Event::Preedit` event does not trigger a redraw request when the preedit content is empty.

The expected v.s. actual preedit content state transition is:

- Expected: `Some("あ")` →  `Some("あい")` →  `Some("あいう")` →  `Some("あいうえ")` →  `Some("あいうえお")` →  `Some("")` → `None`
- Expected: `Some("あ")` →  `Some("あい")` →  `Some("あいう")` →  `Some("あいうえ")` →  `Some("あいうえお")` → `None`

**Comment by hecrj** [comment]
I see! Good catch!

**Review by hecrj — APPROVED** [review]

**Comment by rhysd** [comment]
@hecrj I tried to fix the issue at 89a4dc2 by clearing the pre-edit state when the pre-edit content is `None` (Previously it was cleared only when the content is an empty string).

At least I confirmed the bug was fixed on Windows and I didn't observe any regression on macOS using `TextInput`.

**Comment by hecrj** [comment]
@rhysd Yep, that's the right fix! I removed that case accidentally.

Thanks for testing!
